spring:
  datasource:
    url: jdbc:mysql://101.37.20.199:3306/online-judge
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: 2256788742@qq.com
    password: dpqdeylkbudtecgb
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  map-undersccore-to-camel-case: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  tracker-list:
    - 101.37.20.199:22122
server:
  port: 8088
#线程池配置参数
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 20  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量